kb(colorAmarillo(yes,pikachu)).
kb(colorAmarillo(no,gyarados)).
kb(colorAmarillo(yes,psyduck)).
kb(colorAmarillo(no,ditto)).
kb(colorAmarillo(yes,pidgey)).
kb(colorAmarillo(no,snorlax)).
kb(colorAmarillo(no,magikarp)).
kb(colorAmarillo(no,rayquaza)).
kb(colorAmarillo(yes,combee)).
kb(colorAmarillo(no,tyranitar)).
kb(colorAmarillo(no,togepi)).
kb(colorAmarillo(no,caterpie)).
kb(colorAmarillo(no,spoink)).
kb(colorAmarillo(no,rattata)).
kb(colorAmarillo(no,clamperl)).
kb(colorAmarillo(yes,dragonite)).
kb(colorAmarillo(no,cloyster)).
kb(colorAmarillo(yes,zapdos)).
kb(colorAmarillo(no,charizard)).
kb(colorVerde(no,pikachu)).
kb(colorVerde(no,gyarados)).
kb(colorVerde(no,psyduck)).
kb(colorVerde(no,ditto)).
kb(colorVerde(no,pidgey)).
kb(colorVerde(no,snorlax)).
kb(colorVerde(no,magikarp)).
kb(colorVerde(yes,rayquaza)).
kb(colorVerde(no,combee)).
kb(colorVerde(yes,tyranitar)).
kb(colorVerde(no,togepi)).
kb(colorVerde(yes,caterpie)).
kb(colorVerde(no,spoink)).
kb(colorVerde(no,rattata)).
kb(colorVerde(no,clamperl)).
kb(colorVerde(no,dragonite)).
kb(colorVerde(no,cloyster)).
kb(colorVerde(no,zapdos)).
kb(colorVerde(no,charizard)).
kb(tipoElectrico(yes,pikachu)).
kb(tipoElectrico(no,gyarados)).
kb(tipoElectrico(no,psyduck)).
kb(tipoElectrico(no,ditto)).
kb(tipoElectrico(no,pidgey)).
kb(tipoElectrico(no,snorlax)).
kb(tipoElectrico(no,magikarp)).
kb(tipoElectrico(no,rayquaza)).
kb(tipoElectrico(no,combee)).
kb(tipoElectrico(no,tyranitar)).
kb(tipoElectrico(no,togepi)).
kb(tipoElectrico(no,caterpie)).
kb(tipoElectrico(no,spoink)).
kb(tipoElectrico(no,rattata)).
kb(tipoElectrico(no,clamperl)).
kb(tipoElectrico(no,dragonite)).
kb(tipoElectrico(no,cloyster)).
kb(tipoRoca(no,pikachu)).
kb(tipoRoca(no,gyarados)).
kb(tipoRoca(no,psyduck)).
kb(tipoRoca(no,ditto)).
kb(tipoRoca(no,pidgey)).
kb(tipoRoca(no,snorlax)).
kb(tipoRoca(no,magikarp)).
kb(tipoRoca(no,rayquaza)).
kb(tipoRoca(no,combee)).
kb(tipoRoca(yes,tyranitar)).
kb(tipoRoca(no,togepi)).
kb(tipoRoca(no,caterpie)).
kb(tipoRoca(no,spoink)).
kb(tipoRoca(no,rattata)).
kb(tipoRoca(no,clamperl)).
kb(tipoRoca(no,dragonite)).
kb(tipoRoca(no,cloyster)).
kb(legendario(no,pikachu)).
kb(legendario(no,gyarados)).
kb(legendario(no,psyduck)).
kb(legendario(no,ditto)).
kb(legendario(no,pidgey)).
kb(legendario(no,snorlax)).
kb(legendario(no,magikarp)).
kb(legendario(yes,rayquaza)).
kb(legendario(no,combee)).
kb(legendario(no,tyranitar)).
kb(legendario(no,togepi)).
kb(legendario(no,caterpie)).
kb(legendario(no,spoink)).
kb(legendario(no,rattata)).
kb(legendario(no,clamperl)).
kb(legendario(no,dragonite)).
kb(legendario(no,cloyster)).
kb(legendario(yes,zapdos)).
kb(legendario(no,charizard)).
kb(generacionUno(yes,pikachu)).
kb(generacionUno(yes,gyarados)).
kb(generacionUno(yes,psyduck)).
kb(generacionUno(yes,ditto)).
kb(generacionUno(yes,pidgey)).
kb(generacionUno(yes,snorlax)).
kb(generacionUno(yes,magikarp)).
kb(generacionUno(no,rayquaza)).
kb(generacionUno(no,combee)).
kb(generacionUno(no,tyranitar)).
kb(generacionUno(no,togepi)).
kb(generacionUno(yes,caterpie)).
kb(generacionUno(no,spoink)).
kb(generacionUno(yes,rattata)).
kb(generacionUno(no,clamperl)).
kb(generacionUno(yes,dragonite)).
kb(generacionUno(yes,cloyster)).
kb(generacionUno(yes,zapdos)).
kb(generacionUno(yes,charizard)).
kb(generacionDos(no,pikachu)).
kb(generacionDos(no,gyarados)).
kb(generacionDos(no,psyduck)).
kb(generacionDos(no,ditto)).
kb(generacionDos(no,pidgey)).
kb(generacionDos(no,snorlax)).
kb(generacionDos(no,magikarp)).
kb(generacionDos(no,rayquaza)).
kb(generacionDos(no,combee)).
kb(generacionDos(yes,tyranitar)).
kb(generacionDos(yes,togepi)).
kb(generacionDos(no,caterpie)).
kb(generacionDos(no,spoink)).
kb(generacionDos(no,rattata)).
kb(generacionDos(no,clamperl)).
kb(generacionDos(no,dragonite)).
kb(generacionDos(no,cloyster)).
kb(generacionDos(no,zapdos)).
kb(generacionDos(no,charizard)).
kb(primerEvolucion(no,pikachu)).
kb(primerEvolucion(no,gyarados)).
kb(primerEvolucion(yes,psyduck)).
kb(primerEvolucion(no,ditto)).
kb(primerEvolucion(yes,pidgey)).
kb(primerEvolucion(no,snorlax)).
kb(primerEvolucion(yes,magikarp)).
kb(primerEvolucion(no,rayquaza)).
kb(primerEvolucion(yes,combee)).
kb(primerEvolucion(no,tyranitar)).
kb(primerEvolucion(yes,togepi)).
kb(primerEvolucion(yes,caterpie)).
kb(primerEvolucion(yes,spoink)).
kb(primerEvolucion(yes,rattata)).
kb(primerEvolucion(yes,clamperl)).
kb(primerEvolucion(no,dragonite)).
kb(primerEvolucion(no,cloyster)).
kb(primerEvolucion(no,zapdos)).
kb(primerEvolucion(no,charizard)).
kb(tieneAlas(no,pikachu)).
kb(tieneAlas(no,gyarados)).
kb(tieneAlas(no,psyduck)).
kb(tieneAlas(no,ditto)).
kb(tieneAlas(yes,pidgey)).
kb(tieneAlas(no,snorlax)).
kb(tieneAlas(no,magikarp)).
kb(tieneAlas(no,rayquaza)).
kb(tieneAlas(yes,combee)).
kb(tieneAlas(no,tyranitar)).
kb(tieneAlas(no,togepi)).
kb(tieneAlas(no,caterpie)).
kb(tieneAlas(no,spoink)).
kb(tieneAlas(no,rattata)).
kb(tieneAlas(no,clamperl)).
kb(tieneAlas(yes,dragonite)).
kb(tieneAlas(no,cloyster)).
kb(tieneAlas(yes,zapdos)).
kb(tieneAlas(yes,charizard)).
kb(esRelevanteEnLaMeta(no,pikachu)).
kb(esRelevanteEnLaMeta(yes,gyarados)).
kb(esRelevanteEnLaMeta(no,psyduck)).
kb(esRelevanteEnLaMeta(yes,ditto)).
kb(esRelevanteEnLaMeta(no,pidgey)).
kb(esRelevanteEnLaMeta(yes,snorlax)).
kb(esRelevanteEnLaMeta(no,magikarp)).
kb(esRelevanteEnLaMeta(yes,rayquaza)).
kb(esRelevanteEnLaMeta(no,combee)).
kb(esRelevanteEnLaMeta(yes,tyranitar)).
kb(esRelevanteEnLaMeta(no,togepi)).
kb(esRelevanteEnLaMeta(no,caterpie)).
kb(esRelevanteEnLaMeta(no,spoink)).
kb(esRelevanteEnLaMeta(no,rattata)).
kb(esRelevanteEnLaMeta(no,clamperl)).
kb(esRelevanteEnLaMeta(yes,dragonite)).
kb(esRelevanteEnLaMeta(no,cloyster)).
kb(esRelevanteEnLaMeta(yes,zapdos)).
kb(esRelevanteEnLaMeta(yes,charizard)).
