sobre(nada,cajachicoamarilla).
sobre(nada,cilindrograndeamarillo).
tamano(cajachicoamarilla,chico). 
tipo(cajachicoamarilla,caja). 
estado(cajachicoamarilla,closed). 
color(cajachicoamarilla,amarilla). 
sobre(cajachicoamarilla,cubomedianorojo).
tamano(cilindrograndeamarillo,grande). 
tipo(cilindrograndeamarillo,cilindro). 
color(cilindrograndeamarillo,amarillo). 
sobre(cilindrograndeamarillo,piso). 
tamano(cubograndeazul,grande). 
tipo(cubograndeazul,cubo). 
color(cubograndeazul,azul). 
sobre(cubograndeazul,piso). 
tamano(cubomedianorojo,mediano). 
tipo(cubomedianorojo,cubo). 
color(cubomedianorojo,rojo). 
sobre(cubomedianorojo,cubograndeazul).
